# Downloading Dataset

In [1]:
!wget --header="Host: storage.googleapis.com" --header="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3" --header="Accept-Language: en-US,en;q=0.9" --header="Referer: https://www.kaggle.com/" --header="Cookie: cuntwars_user_id=vFHd55haQ6; _ga=GA1.3.1069537971.1546461315; __utma=68291539.1069537971.1546461315.1547285225.1547285225.1; __utmz=68291539.1547285225.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)" --header="Connection: keep-alive" "https://storage.googleapis.com/kaggle-datasets/57177/110068/simpsons-faces.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1559015829&Signature=LGDOQFHvtDsROQZUdjfU8QAK6JdlW2cI5ougkRBIpQFqPHDDHfafajAmNIyO4mA0AhOLaFCASF%2Bd8MAOmyX0KFKFpAsDvBxflgFMwHRLUUBo9jQHkguG6apUQnrfXXQ%2FigX%2F14gPZxDwFrYAnsERA%2FzNeNQI5F7PrACdRtmNz42jQNrY9tG9oFh%2BOqKwlG%2BOpD4huJ6x%2FnPUjPbp1QSNCgc9VL6cMMo6W4doHpXCm%2BzDaarkJqY%2Bf14mtHGTXPDuV3h7a9um%2BteDxC756mGVlAG09KqRWMvorgkL7cm%2FmBR2M%2BqN4iNWy4ABtpvl5zl%2BItxQj5Xj4AHpSa90bZs3TA%3D%3D" -O "simpsons-faces.zip" -c

--2019-05-25 17:41:00--  https://storage.googleapis.com/kaggle-datasets/57177/110068/simpsons-faces.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1559015829&Signature=LGDOQFHvtDsROQZUdjfU8QAK6JdlW2cI5ougkRBIpQFqPHDDHfafajAmNIyO4mA0AhOLaFCASF%2Bd8MAOmyX0KFKFpAsDvBxflgFMwHRLUUBo9jQHkguG6apUQnrfXXQ%2FigX%2F14gPZxDwFrYAnsERA%2FzNeNQI5F7PrACdRtmNz42jQNrY9tG9oFh%2BOqKwlG%2BOpD4huJ6x%2FnPUjPbp1QSNCgc9VL6cMMo6W4doHpXCm%2BzDaarkJqY%2Bf14mtHGTXPDuV3h7a9um%2BteDxC756mGVlAG09KqRWMvorgkL7cm%2FmBR2M%2BqN4iNWy4ABtpvl5zl%2BItxQj5Xj4AHpSa90bZs3TA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.24.128, 2404:6800:4003:c04::80
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.24.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 462484599 (441M) [application/zip]
Saving to: ‘simpsons-faces.zip’

simpsons-faces.zip  100%[===================>] 441.06M  35.2MB/s    in 12s     

2019-05-25 17:41:13 (35.8 MB/s) 

In [2]:
!unzip 'simpsons-faces.zip'

Archive:  simpsons-faces.zip
  inflating: cropped.zip             
  inflating: simplified.zip          


In [3]:
!mkdir 'cropped'
!unzip 'cropped.zip' -d '/content/cropped'

!mkdir 'simplified'
!unzip 'simplified.zip' -d '/content/simplified'

Archive:  cropped.zip
  inflating: /content/cropped/3975.png  
  inflating: /content/cropped/8820.png  
  inflating: /content/cropped/9280.png  
  inflating: /content/cropped/348.png  
  inflating: /content/cropped/1804.png  
  inflating: /content/cropped/4968.png  
  inflating: /content/cropped/9294.png  
  inflating: /content/cropped/1810.png  
  inflating: /content/cropped/6819.png  
  inflating: /content/cropped/8834.png  
  inflating: /content/cropped/3961.png  
  inflating: /content/cropped/6831.png  
  inflating: /content/cropped/1186.png  
  inflating: /content/cropped/412.png  
  inflating: /content/cropped/3949.png  
  inflating: /content/cropped/3791.png  
  inflating: /content/cropped/4798.png  
  inflating: /content/cropped/4940.png  
  inflating: /content/cropped/5486.png  
  inflating: /content/cropped/374.png  
  inflating: /content/cropped/1838.png  
  inflating: /content/cropped/7291.png  
  inflating: /content/cropped/360.png  
  inflating: /content/cropped/7285.png 

In [0]:
!rm -rf 'cropped/__MACOSX'
!rm -rf 'simplified/__MACOSX'

# Building Model

In [1]:
from __future__ import print_function, division

from keras.datasets import mnist
from keras.layers import Dense, Dropout, Conv2DTranspose, Flatten, Reshape, Input, BatchNormalization, Activation, ZeroPadding2D, MaxPooling2D, AveragePooling2D
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.convolutional import UpSampling2D, Conv2D
from keras.models import Model, Sequential
from keras.optimizers import Adam

import matplotlib.pyplot as plt
import numpy as np
import sys
import os as os
import tensorflow as tf

Using TensorFlow backend.


In [2]:
latent_dim = 100
nh = 128
nw = 128
nc = 3
img_shape = (nh, nw, nc)

d_opt = Adam(lr = 0.00004, beta_1 = 0.5)
g_opt = Adam(lr = 0.0004, beta_1 = 0.5)

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
def build_generator():
  
  model = Sequential()
  
  model.add(Dense(1024 * 8 * 8, activation="relu", input_dim = latent_dim))
  model.add(Reshape((8, 8, 1024)))
  model.add(LeakyReLU())
  
  model.add(Conv2DTranspose(filters=512, kernel_size=[5,5], strides=[2,2], padding="SAME", kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), name="trans_conv1"))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2DTranspose(filters=256, kernel_size=[5,5], strides=[2,2], padding="SAME", kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), name="trans_conv2"))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2DTranspose(filters=128, kernel_size=[5,5], strides=[2,2], padding="SAME", kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), name="trans_conv3"))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2DTranspose(filters=64, kernel_size=[5,5], strides=[2,2], padding="SAME", kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), name="trans_conv4"))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2DTranspose(filters=3, kernel_size=[5,5], strides=[1,1], padding="SAME", kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), name="trans_conv5"))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(Activation('tanh'))
  
  
  print(model.summary())
  
  noise = Input(shape = (latent_dim,))
  img = model(noise)
  
  return Model(inputs = noise, outputs = img)
  

In [4]:
generator = build_generator()
generator.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 65536)             6619136   
_________________________________________________________________
reshape_1 (Reshape)          (None, 8, 8, 1024)        0         
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 8, 8, 1024)        0         
_________________________________________________________________
trans_conv1 (Conv2DTranspose (None, 16, 16, 512)       13107712  
_________________________________________________________________
batch_normalization_1 (Batch (None, 16, 16, 512)       2048      
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 16, 16, 512)       0         
_________________________________________________________________
trans_conv2 (Conv2DTranspose (None, 32, 32, 256)       3277056   
__________

In [0]:
def build_discriminator():
  model = Sequential()
  
  model.add(Conv2D(64, kernel_size = 5, strides = 2, input_shape = img_shape, kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), padding = 'same'))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2D(128, kernel_size = 5, strides = 2, input_shape = img_shape, kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), padding = 'same'))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2D(256, kernel_size = 5, strides = 2, input_shape = img_shape, kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), padding = 'same'))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2D(512, kernel_size = 5, strides = 1, input_shape = img_shape, kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), padding = 'same'))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Conv2D(1024, kernel_size = 5, strides = 2, input_shape = img_shape, kernel_initializer=tf.truncated_normal_initializer(stddev=0.02), padding = 'same'))
  model.add(BatchNormalization(epsilon=0.00005))
  model.add(LeakyReLU())
  
  model.add(Flatten())
  model.add(Dense(1, activation = 'sigmoid'))
  
  print(model.summary())
  
  img = Input(shape = img_shape)
  validity = model(img)
  
  return Model(inputs = img, outputs = validity)

In [6]:
discriminator = build_discriminator()
discriminator.summary()

discriminator.compile(loss = 'binary_crossentropy', optimizer = d_opt, metrics = ['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 64, 64, 64)        4864      
_________________________________________________________________
batch_normalization_6 (Batch (None, 64, 64, 64)        256       
_________________________________________________________________
leaky_re_lu_6 (LeakyReLU)    (None, 64, 64, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 128)       204928    
_________________________________________________________________
batch_normalization_7 (Batch (None, 32, 32, 128)       512       
_________________________________________________________________
leaky_re_lu_7 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 256)       819456    
__________

In [7]:
z = Input(shape = (latent_dim,))
img = generator(z)

discriminator.trainable = False
valid = discriminator(img)

combined = Model(z, valid)
combined.compile(loss = 'binary_crossentropy', optimizer = g_opt)
combined.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 100)               0         
_________________________________________________________________
model_1 (Model)              (None, 128, 128, 3)       24036751  
_________________________________________________________________
model_2 (Model)              (None, 1)                 17488257  
Total params: 41,525,008
Trainable params: 24,034,825
Non-trainable params: 17,490,183
_________________________________________________________________


In [8]:
print(generator.summary())
print(discriminator.summary())
print(combined.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 100)               0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 128, 128, 3)       24036751  
Total params: 24,036,751
Trainable params: 24,034,825
Non-trainable params: 1,926
_________________________________________________________________
None
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 128, 128, 3)       0         
_________________________________________________________________
sequential_2 (Sequential)    (None, 1)                 17488257  
Total params: 34,972,546
Trainable params: 17,484,289
Non-trainable params: 17,488,257
_________________________________________________________________
None
_____________________________

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


In [0]:
import numpy as np
from tqdm import tqdm
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import tensorflow as tf
from numpy import random

def train(batch_size = 256, epochs = 4000):
  
  X_train = np.zeros((9858, np.int32(nh), nw, nc), dtype = 'float32')
  
  count = 0
  
  for i in tqdm(os.listdir('simplified')[:9858]):
    img = Image.open('simplified/'+i).resize((np.int32(nh), np.int32(nw)))
    X_train[count] = np.array(img, dtype = np.float32)
    img.close()
  
  X_train = X_train/127.5 - 1
  print(X_train[0])
  print(X_train.shape)

  valid = np.ones((batch_size, 1))
  fakes = np.zeros((batch_size, 1))
  
  for epoch in range(epochs):
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    imgs = X_train[idx] + tf.random_normal(shape=tf.shape(X_train[idx]),
                                                     mean=0.0,
                                                     stddev=random.uniform(0.0, 0.1),
                                                     dtype=tf.float32)
    
    noise = np.random.normal(0, 1, (batch_size, latent_dim))
    gen_imgs = generator.predict(noise)
    
    #Training Discriminator
    d_loss_real = discriminator.train_on_batch(imgs, valid)
    d_loss_fake = discriminator.train_on_batch(gen_imgs, fakes)
    d_loss = 0.5*np.add(d_loss_real, d_loss_fake)
    
    #Training Generator
    g_loss = combined.train_on_batch(noise, valid)
    
    #Progress
    print("epoch: " + str(epoch) + " " + "D_Loss = " + str(d_loss[0]) + " " + "acc: " + str(d_loss[1]*100) + " " +  "G_Loss = " + str(g_loss))

In [10]:
train(64,300)

100%|██████████| 9858/9858 [00:13<00:00, 739.47it/s]


[[[-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  ...
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]]

 [[-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  ...
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]]

 [[-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  ...
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]]

 ...

 [[-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  ...
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]
  [-0.21568626  0.33333337  0.4901961 ]]

 [

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


epoch: 0 D_Loss = 1.2111313 acc: 35.15625 G_Loss = 1.7211945
epoch: 1 D_Loss = 4.0978856 acc: 50.0 G_Loss = 0.24994478
epoch: 2 D_Loss = 3.1735766 acc: 50.0 G_Loss = 1.2382969
epoch: 3 D_Loss = 3.0012372 acc: 50.0 G_Loss = 1.9507886
epoch: 4 D_Loss = 2.4421287 acc: 50.0 G_Loss = 3.0640216
epoch: 5 D_Loss = 1.2089512 acc: 56.25 G_Loss = 4.804094
epoch: 6 D_Loss = 1.3677449 acc: 54.6875 G_Loss = 4.9724984
epoch: 7 D_Loss = 0.46751565 acc: 75.78125 G_Loss = 5.362792
epoch: 8 D_Loss = 0.8429006 acc: 62.5 G_Loss = 4.599966
epoch: 9 D_Loss = 1.2435185 acc: 57.03125 G_Loss = 5.8358617
epoch: 10 D_Loss = 0.3289018 acc: 86.71875 G_Loss = 4.197772
epoch: 11 D_Loss = 0.8844733 acc: 66.40625 G_Loss = 6.1269255
epoch: 12 D_Loss = 0.23634507 acc: 91.40625 G_Loss = 4.1970997
epoch: 13 D_Loss = 1.1547529 acc: 60.9375 G_Loss = 5.8018136
epoch: 14 D_Loss = 0.5684042 acc: 74.21875 G_Loss = 4.719121
epoch: 15 D_Loss = 0.92020756 acc: 65.625 G_Loss = 7.6478996
epoch: 16 D_Loss = 0.25923258 acc: 86.71875 G_

In [11]:
!mkdir 'images'

mkdir: cannot create directory ‘images’: File exists


In [0]:
def save_imgs(epoch):
  r, c = 5, 5
  noise = np.random.normal(0, 1, (r * c, latent_dim))
  gen_imgs = generator.predict(noise)
  print(gen_imgs[0])
  
  # Rescale images 0 - 1
  #for i in range(len(gen_imgs)):
  #  gen_imgs[i] = scale_img(unpreprocess(gen_imgs[i]))

  gen_imgs = ((gen_imgs+1.)*127.5).astype(np.uint8)
  print(gen_imgs[0])
  
  fig, axs = plt.subplots(r, c)
  cnt = 0
  for i in range(r):
     for j in range(c):
        axs[i,j].imshow(gen_imgs[cnt, :,:,0])
        axs[i,j].axis('off')
        cnt += 1
  fig.savefig("images/mnist_%d.png" % epoch)
  plt.close()

In [13]:
from PIL import Image

noise = np.random.normal(0, 1, (1, latent_dim))
gen_imgs = generator.predict(noise)
print(gen_imgs[0])
  
# Rescale images 0 - 1
#for i in range(len(gen_imgs)):
#  gen_imgs[i] = scale_img(unpreprocess(gen_imgs[i]))

gen_imgs = ((gen_imgs+1.)*127.5).astype(np.uint8)
print(gen_imgs[0])

gen_imgs = gen_imgs[0]
image = Image.fromarray(gen_imgs)
image.save('1.png')

[[[-1.85140222e-02 -1.18040048e-01 -2.18806222e-01]
  [ 5.91324409e-03 -5.09607373e-03 -1.22022808e-01]
  [-2.92861611e-01  1.34184897e-01 -1.55860737e-01]
  ...
  [-4.91843969e-01 -7.72280514e-01  5.31713843e-01]
  [-5.12569308e-01 -1.42379552e-01 -3.50592643e-01]
  [-3.78757507e-01 -4.61213022e-01 -3.43755782e-02]]

 [[-2.39125490e-01  1.98155642e-03 -3.55209038e-02]
  [-6.54581189e-01 -7.71182552e-02 -4.15923685e-01]
  [-3.49458605e-01  3.14623713e-01  1.63247898e-01]
  ...
  [-8.92994881e-01 -2.95248955e-01  5.25028169e-01]
  [-3.63760570e-04  6.37955731e-03  4.92679715e-01]
  [-4.08235699e-01 -4.97110784e-01  4.64571208e-01]]

 [[ 2.88846195e-01 -1.55747135e-03 -1.17726505e-01]
  [-1.89893663e-01 -3.94878894e-01 -1.57942161e-01]
  [ 7.05900669e-01  2.24394262e-01 -2.35098884e-01]
  ...
  [-7.10695684e-01 -8.36884141e-01  6.90957665e-01]
  [ 9.76543188e-01  9.43394244e-01 -6.13924205e-01]
  [ 2.15424359e-01  5.14079094e-01  3.93953919e-01]]

 ...

 [[-4.61222112e-01 -2.05249071e-01